# Generated by Django 2.0.2 on 2018-03-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=500)),
                ('karma', models.SmallIntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_file', models.FileField(upload_to='../media/notes/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='../media/thumbnails/')),
                ('title', models.CharField(max_length=180, verbose_name='Title')),
                ('semester', models.CharField(max_length=40, verbose_name='Semester')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('karma', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['note_id'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_pic', models.ImageField(upload_to='../media/profiles/')),
                ('karma', models.SmallIntegerField(default=0)),
                ('course_schedule', models.ManyToManyField(blank=True, related_name='course_schedule', to='note_app.Course')),
                ('favorite_authors', models.ManyToManyField(blank=True, related_name='_profile_favorite_authors_+', to='note_app.Profile')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='note_app.Note')),
                ('post_history', models.ManyToManyField(blank=True, related_name='post_history', to='note_app.Comment')),
                ('uploaded', models.ManyToManyField(blank=True, related_name='uploaded', to='note_app.Note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['profile_id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Profile'),
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='note_app.Comment'),
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Course'),
        ),
        migrations.AddField(
            model_name='note',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.School'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_app.Note'),
        ),
    ]
