# Generated by Django 2.0.2 on 2018-03-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
    ]
