# Generated by Django 2.0.2 on 2018-03-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_auto_20180329_1751'),
    ]

    operations = [
    ]
